spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://slave2:3306/testMyBatisPlus?autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&serverTimezone=UTC
server:
  port: 8080
